steps:
- name: 'docker/compose:1.19.0'
  args: [ '-f', 'docker/docker-compose.yml', 'up', '-d' ]
- name: 'maven:3-openjdk-17'
  entrypoint: 'mvn'
  args: ['install']
  env:
  - 'ELASTIC_HOST=elasticsearch'
  - 'MONGO_HOST=mongo'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/wellynews', '.']
- name: 'docker/compose:1.19.0'
  args: [ '-f', 'docker/docker-compose.yml', 'down' ]
images:
  - 'eu.gcr.io/$PROJECT_ID/wellynews'