services:
  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    volumes:
    - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
    - "9200:9200"
  mongo:
    image: mongo:3.2
    ports:
    - "27017:27017"
