version: '3'
services:
  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    volumes:
    - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
    - "9200:9200"
  memcached:
    image: memcached
    ports:
    - "11211:11211"
  mongo:
    image: mongo:3.4
    ports:
    - "27017:27017"
  rabbit:
    image: rabbitmq:3
    ports:
    - "5672:5672"
networks:
  default:
    external:
      name: cloudbuild